echo $warnings_are_errors

# Install R dependencies
R -e "devtools::install_deps('.', c('Depends', 'Imports', 'Suggests'))"

# Build package
R CMD build .

# Check package
PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
R CMD check "${PKG_FILE_NAME}"

# Failure if any error, warning or note
RCHECK_DIR=$(ls -1t *.tar.gz | head -n 1 | cut -d'_' -f 1).Rcheck
LAST_LINE=$(tail -1 ${RCHECK_DIR}/00check.log)
if [ "${LAST_LINE}" != "Status: OK" ]; then exit 1 ; fi