variables:
  GIT_SSL_NO_VERIFY: "1"
  warnings_are_errors: TRUE

R-CMD-check: 
  image: git.stable.innovation.insee.eu:50000/innovation/rstudio
  script: sh .gitlab-ci.script
  artifacts:
    paths: 
      - "*.tar.gz"
    